name = "emailer-cod-contact"
main = "worker/index.js"
compatibility_date = "2026-06-01"


routes = [
  { pattern = "api.cheltenham-od.uk/contact*", zone_name = "cheltenham-od.uk" }
]

[vars]
ALLOWED_ORIGIN = "https://cheltenham-od.uk"
THANKYOU_URL = "https:/cheltenham-od.uk/form/thanks"
ERROR_URL = "https://cheltenham-od.uk/form/error"

[observability.logs]
enabled = true
invocation_logs = true
